name: Fetch AI News

on:
  workflow_dispatch:  # This enables manual triggering
  schedule:
    # Runs at 19:00 GMT (7 PM GMT) every day
    - cron: '0 01 * * *'

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('vader_lexicon')"
        
    - name: Run news fetcher script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PYTHONUNBUFFERED: "1"
      run: python -u ainews.py
        
    - name: Configure Git
      run: |
        git config --local user.email "${{ secrets.GIT_EMAIL }}"
        git config --local user.name "${{ secrets.GIT_USERNAME }}"
        
    - name: Commit and push if there are changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git add news/
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        git commit -m "Update AI news: ${timestamp}" || exit 0
        git push origin HEAD:main

    - name: Check for errors
      if: failure()
      run: |
        echo "Workflow failed. Please check the logs for errors."
